#!/usr/bin/env sh

set -e
rm -rf build/local-pre-push
mkdir -p build/local-pre-push
cmake -H. -Bbuild/local-pre-push
cd build/local-pre-push
make -j8 check_and_upload
cd ../..

docker-compose --env-file docker/upload.env -f docker/docker-compose.yml run test-clang_10-ubuntu_20.04
