// REQUEST:NO_TEST_LIB "The testing library depends on <type_traits>."

#include <type_traits>

#include "meta/test_unary_trait.h"

DECLARE_TRAIT_V_READER(is_object_v);

TEST_UNARY_TRAIT_AGAINST_VOID(false, is_object, EVERY_CV);
TEST_UNARY_TRAIT_AGAINST_NULLPTR_T(true, is_object, EVERY_CV);
TEST_UNARY_TRAIT_AGAINST_INTEGRAL(true, is_object, EVERY_CV);
TEST_UNARY_TRAIT_AGAINST_FLOATING_POINT(true, is_object, EVERY_CV);
TEST_UNARY_TRAIT_AGAINST_ARRAY(true, is_object, EVERY_CV);
TEST_UNARY_TRAIT_AGAINST_POINTER(true, is_object, EVERY_CV);
TEST_UNARY_TRAIT_AGAINST_LVALUE_REFERENCE(false, is_object);
TEST_UNARY_TRAIT_AGAINST_RVALUE_REFERENCE(false, is_object);
TEST_UNARY_TRAIT_AGAINST_MEMBER_OBJECT_POINTER(true, is_object, EVERY_CV);
TEST_UNARY_TRAIT_AGAINST_MEMBER_FUNCTION_POINTER(true, is_object, EVERY_CV);
TEST_UNARY_TRAIT_AGAINST_ENUM(true, is_object, EVERY_CV);
TEST_UNARY_TRAIT_AGAINST_UNION(true, is_object, EVERY_CV);
TEST_UNARY_TRAIT_AGAINST_CLASS(true, is_object, EVERY_CV);
TEST_UNARY_TRAIT_AGAINST_FUNCTION(false, is_object);

int main() {
    return 0;
}
