#include <compare>

#include "testing.h"

constexpr bool implicit_conversion_to_partial_ordering(std::partial_ordering) noexcept {
    return true;
}

TEST(less) {
    ASSERT_TYPE(const std::weak_ordering&, std::weak_ordering::less);
    ASSERT_CT_RT(implicit_conversion_to_partial_ordering(std::weak_ordering::less));
    ASSERT_CT_RT(std::weak_ordering::less == std::partial_ordering::less);
    ASSERT_CT_RT(static_cast<std::partial_ordering>(std::weak_ordering::less) == std::partial_ordering::less);
    ASSERT_NOEXCEPT(static_cast<std::partial_ordering>(std::weak_ordering::less));
    ASSERT_CT_RT(std::weak_ordering::less == std::weak_ordering::less);
    ASSERT_NOEXCEPT(std::weak_ordering::less == std::weak_ordering::less);
    ASSERT_CT_RT(!(std::weak_ordering::less == std::weak_ordering::equivalent));
    ASSERT_NOEXCEPT(std::weak_ordering::less == std::weak_ordering::equivalent);
    ASSERT_CT_RT(!(std::weak_ordering::less == std::weak_ordering::greater));
    ASSERT_NOEXCEPT(std::weak_ordering::less == std::weak_ordering::greater);
    ASSERT_CT_RT(!(std::weak_ordering::less != std::weak_ordering::less));
    ASSERT_NOEXCEPT(std::weak_ordering::less != std::weak_ordering::less);
    ASSERT_CT_RT(std::weak_ordering::less != std::weak_ordering::equivalent);
    ASSERT_NOEXCEPT(std::weak_ordering::less != std::weak_ordering::equivalent);
    ASSERT_CT_RT(std::weak_ordering::less != std::weak_ordering::greater);
    ASSERT_NOEXCEPT(std::weak_ordering::less != std::weak_ordering::greater);
    ASSERT_CT_RT(!(std::weak_ordering::equivalent == std::weak_ordering::less));
    ASSERT_NOEXCEPT(std::weak_ordering::equivalent == std::weak_ordering::less);
    ASSERT_CT_RT(!(std::weak_ordering::greater == std::weak_ordering::less));
    ASSERT_NOEXCEPT(std::weak_ordering::greater == std::weak_ordering::less);
    ASSERT_CT_RT(std::weak_ordering::equivalent != std::weak_ordering::less);
    ASSERT_NOEXCEPT(std::weak_ordering::equivalent != std::weak_ordering::less);
    ASSERT_CT_RT(std::weak_ordering::greater != std::weak_ordering::less);
    ASSERT_NOEXCEPT(std::weak_ordering::greater != std::weak_ordering::less);
    ASSERT_CT_RT(!(std::weak_ordering::less == 0));
    ASSERT_NOEXCEPT(std::weak_ordering::less == 0);
    ASSERT_CT_RT(std::weak_ordering::less != 0);
    ASSERT_NOEXCEPT(std::weak_ordering::less != 0);
    ASSERT_CT_RT(std::weak_ordering::less < 0);
    ASSERT_NOEXCEPT(std::weak_ordering::less < 0);
    ASSERT_CT_RT(!(std::weak_ordering::less > 0));
    ASSERT_NOEXCEPT(std::weak_ordering::less > 0);
    ASSERT_CT_RT(std::weak_ordering::less <= 0);
    ASSERT_NOEXCEPT(std::weak_ordering::less <= 0);
    ASSERT_CT_RT(!(std::weak_ordering::less >= 0));
    ASSERT_NOEXCEPT(std::weak_ordering::less >= 0);
    ASSERT_CT_RT(!(0 == std::weak_ordering::less));
    ASSERT_NOEXCEPT(0 == std::weak_ordering::less);
    ASSERT_CT_RT(0 != std::weak_ordering::less);
    ASSERT_NOEXCEPT(0 != std::weak_ordering::less);
    ASSERT_CT_RT(!(0 < std::weak_ordering::less));
    ASSERT_NOEXCEPT(0 < std::weak_ordering::less);
    ASSERT_CT_RT(0 > std::weak_ordering::less);
    ASSERT_NOEXCEPT(0 > std::weak_ordering::less);
    ASSERT_CT_RT(!(0 <= std::weak_ordering::less));
    ASSERT_NOEXCEPT(0 <= std::weak_ordering::less);
    ASSERT_CT_RT(0 >= std::weak_ordering::less);
    ASSERT_NOEXCEPT(0 >= std::weak_ordering::less);
    ASSERT_CT_RT((std::weak_ordering::less <=> 0) == std::weak_ordering::less);
    ASSERT_NOEXCEPT(std::weak_ordering::less <=> 0);
    ASSERT_CT_RT((0 <=> std::weak_ordering::less) == std::weak_ordering::greater);
    ASSERT_NOEXCEPT(0 <=> std::weak_ordering::less);
}

TEST(equivalent) {
    ASSERT_TYPE(const std::weak_ordering&, std::weak_ordering::equivalent);
    ASSERT_CT_RT(implicit_conversion_to_partial_ordering(std::weak_ordering::equivalent));
    ASSERT_CT_RT(std::weak_ordering::equivalent == std::partial_ordering::equivalent);
    ASSERT_CT_RT(static_cast<std::partial_ordering>(std::weak_ordering::equivalent) == std::partial_ordering::equivalent);
    ASSERT_NOEXCEPT(static_cast<std::partial_ordering>(std::weak_ordering::equivalent));
    ASSERT_CT_RT(!(std::weak_ordering::equivalent == std::weak_ordering::less));
    ASSERT_NOEXCEPT(std::weak_ordering::equivalent == std::weak_ordering::less);
    ASSERT_CT_RT(std::weak_ordering::equivalent == std::weak_ordering::equivalent);
    ASSERT_NOEXCEPT(std::weak_ordering::equivalent == std::weak_ordering::equivalent);
    ASSERT_CT_RT(!(std::weak_ordering::equivalent == std::weak_ordering::greater));
    ASSERT_NOEXCEPT(std::weak_ordering::equivalent == std::weak_ordering::greater);
    ASSERT_CT_RT(std::weak_ordering::equivalent != std::weak_ordering::less);
    ASSERT_NOEXCEPT(std::weak_ordering::equivalent != std::weak_ordering::less);
    ASSERT_CT_RT(!(std::weak_ordering::equivalent != std::weak_ordering::equivalent));
    ASSERT_NOEXCEPT(std::weak_ordering::equivalent != std::weak_ordering::equivalent);
    ASSERT_CT_RT(std::weak_ordering::equivalent != std::weak_ordering::greater);
    ASSERT_NOEXCEPT(std::weak_ordering::equivalent != std::weak_ordering::greater);
    ASSERT_CT_RT(!(std::weak_ordering::less == std::weak_ordering::equivalent));
    ASSERT_NOEXCEPT(std::weak_ordering::less == std::weak_ordering::equivalent);
    ASSERT_CT_RT(!(std::weak_ordering::greater == std::weak_ordering::equivalent));
    ASSERT_NOEXCEPT(std::weak_ordering::greater == std::weak_ordering::equivalent);
    ASSERT_CT_RT(std::weak_ordering::less != std::weak_ordering::equivalent);
    ASSERT_NOEXCEPT(std::weak_ordering::less != std::weak_ordering::equivalent);
    ASSERT_CT_RT(std::weak_ordering::greater != std::weak_ordering::equivalent);
    ASSERT_NOEXCEPT(std::weak_ordering::greater != std::weak_ordering::equivalent);
    ASSERT_CT_RT(std::weak_ordering::equivalent == 0);
    ASSERT_NOEXCEPT(std::weak_ordering::equivalent == 0);
    ASSERT_CT_RT(!(std::weak_ordering::equivalent != 0));
    ASSERT_NOEXCEPT(std::weak_ordering::equivalent != 0);
    ASSERT_CT_RT(!(std::weak_ordering::equivalent < 0));
    ASSERT_NOEXCEPT(std::weak_ordering::equivalent < 0);
    ASSERT_CT_RT(!(std::weak_ordering::equivalent > 0));
    ASSERT_NOEXCEPT(std::weak_ordering::equivalent > 0);
    ASSERT_CT_RT(std::weak_ordering::equivalent <= 0);
    ASSERT_NOEXCEPT(std::weak_ordering::equivalent <= 0);
    ASSERT_CT_RT(std::weak_ordering::equivalent >= 0);
    ASSERT_NOEXCEPT(std::weak_ordering::equivalent >= 0);
    ASSERT_CT_RT(0 == std::weak_ordering::equivalent);
    ASSERT_NOEXCEPT(0 == std::weak_ordering::equivalent);
    ASSERT_CT_RT(!(0 != std::weak_ordering::equivalent));
    ASSERT_NOEXCEPT(0 != std::weak_ordering::equivalent);
    ASSERT_CT_RT(!(0 < std::weak_ordering::equivalent));
    ASSERT_NOEXCEPT(0 < std::weak_ordering::equivalent);
    ASSERT_CT_RT(!(0 > std::weak_ordering::equivalent));
    ASSERT_NOEXCEPT(0 > std::weak_ordering::equivalent);
    ASSERT_CT_RT(0 <= std::weak_ordering::equivalent);
    ASSERT_NOEXCEPT(0 <= std::weak_ordering::equivalent);
    ASSERT_CT_RT(0 >= std::weak_ordering::equivalent);
    ASSERT_NOEXCEPT(0 >= std::weak_ordering::equivalent);
    ASSERT_CT_RT((std::weak_ordering::equivalent <=> 0) == std::weak_ordering::equivalent);
    ASSERT_NOEXCEPT(std::weak_ordering::equivalent <=> 0);
    ASSERT_CT_RT((0 <=> std::weak_ordering::equivalent) == std::weak_ordering::equivalent);
    ASSERT_NOEXCEPT(0 <=> std::weak_ordering::equivalent);
}

TEST(greater) {
    ASSERT_TYPE(const std::weak_ordering&, std::weak_ordering::greater);
    ASSERT_CT_RT(implicit_conversion_to_partial_ordering(std::weak_ordering::greater));
    ASSERT_CT_RT(std::weak_ordering::greater == std::partial_ordering::greater);
    ASSERT_CT_RT(static_cast<std::partial_ordering>(std::weak_ordering::greater) == std::partial_ordering::greater);
    ASSERT_NOEXCEPT(static_cast<std::partial_ordering>(std::weak_ordering::greater));
    ASSERT_CT_RT(!(std::weak_ordering::greater == std::weak_ordering::less));
    ASSERT_NOEXCEPT(std::weak_ordering::greater == std::weak_ordering::less);
    ASSERT_CT_RT(!(std::weak_ordering::greater == std::weak_ordering::equivalent));
    ASSERT_NOEXCEPT(std::weak_ordering::greater == std::weak_ordering::equivalent);
    ASSERT_CT_RT(std::weak_ordering::greater == std::weak_ordering::greater);
    ASSERT_NOEXCEPT(std::weak_ordering::greater == std::weak_ordering::greater);
    ASSERT_CT_RT(std::weak_ordering::greater != std::weak_ordering::less);
    ASSERT_NOEXCEPT(std::weak_ordering::greater != std::weak_ordering::less);
    ASSERT_CT_RT(std::weak_ordering::greater != std::weak_ordering::equivalent);
    ASSERT_NOEXCEPT(std::weak_ordering::greater != std::weak_ordering::equivalent);
    ASSERT_CT_RT(!(std::weak_ordering::greater != std::weak_ordering::greater));
    ASSERT_NOEXCEPT(std::weak_ordering::greater != std::weak_ordering::greater);
    ASSERT_CT_RT(!(std::weak_ordering::less == std::weak_ordering::greater));
    ASSERT_NOEXCEPT(std::weak_ordering::less == std::weak_ordering::greater);
    ASSERT_CT_RT(!(std::weak_ordering::equivalent == std::weak_ordering::greater));
    ASSERT_NOEXCEPT(std::weak_ordering::equivalent == std::weak_ordering::greater);
    ASSERT_CT_RT(std::weak_ordering::less != std::weak_ordering::greater);
    ASSERT_NOEXCEPT(std::weak_ordering::less != std::weak_ordering::greater);
    ASSERT_CT_RT(std::weak_ordering::equivalent != std::weak_ordering::greater);
    ASSERT_NOEXCEPT(std::weak_ordering::equivalent != std::weak_ordering::greater);
    ASSERT_CT_RT(!(std::weak_ordering::greater == 0));
    ASSERT_NOEXCEPT(std::weak_ordering::greater == 0);
    ASSERT_CT_RT(std::weak_ordering::greater != 0);
    ASSERT_NOEXCEPT(std::weak_ordering::greater != 0);
    ASSERT_CT_RT(!(std::weak_ordering::greater < 0));
    ASSERT_NOEXCEPT(std::weak_ordering::greater < 0);
    ASSERT_CT_RT(std::weak_ordering::greater > 0);
    ASSERT_NOEXCEPT(std::weak_ordering::greater > 0);
    ASSERT_CT_RT(!(std::weak_ordering::greater <= 0));
    ASSERT_NOEXCEPT(std::weak_ordering::greater <= 0);
    ASSERT_CT_RT(std::weak_ordering::greater >= 0);
    ASSERT_NOEXCEPT(std::weak_ordering::greater >= 0);
    ASSERT_CT_RT(!(0 == std::weak_ordering::greater));
    ASSERT_NOEXCEPT(0 == std::weak_ordering::greater);
    ASSERT_CT_RT(0 != std::weak_ordering::greater);
    ASSERT_NOEXCEPT(0 != std::weak_ordering::greater);
    ASSERT_CT_RT(0 < std::weak_ordering::greater);
    ASSERT_NOEXCEPT(0 < std::weak_ordering::greater);
    ASSERT_CT_RT(!(0 > std::weak_ordering::greater));
    ASSERT_NOEXCEPT(0 > std::weak_ordering::greater);
    ASSERT_CT_RT(0 <= std::weak_ordering::greater);
    ASSERT_NOEXCEPT(0 <= std::weak_ordering::greater);
    ASSERT_CT_RT(!(0 >= std::weak_ordering::greater));
    ASSERT_NOEXCEPT(0 >= std::weak_ordering::greater);
    ASSERT_CT_RT((std::weak_ordering::greater <=> 0) == std::weak_ordering::greater);
    ASSERT_NOEXCEPT(std::weak_ordering::greater <=> 0);
    ASSERT_CT_RT((0 <=> std::weak_ordering::greater) == std::weak_ordering::less);
    ASSERT_NOEXCEPT(0 <=> std::weak_ordering::greater);
}
