#include <compare>

#include "testing.h"

constexpr bool implicit_conversion_to_partial_ordering(std::partial_ordering) noexcept {
    return true;
}

constexpr bool implicit_conversion_to_weak_ordering(std::weak_ordering) noexcept {
    return true;
}

TEST(less) {
    ASSERT_TYPE(const std::strong_ordering&, std::strong_ordering::less);
    ASSERT_CT_RT(implicit_conversion_to_partial_ordering(std::strong_ordering::less));
    ASSERT_CT_RT(std::strong_ordering::less == std::partial_ordering::less);
    ASSERT_CT_RT(static_cast<std::partial_ordering>(std::strong_ordering::less) == std::partial_ordering::less);
    ASSERT_NOEXCEPT(static_cast<std::partial_ordering>(std::strong_ordering::less));
    ASSERT_CT_RT(implicit_conversion_to_weak_ordering(std::strong_ordering::less));
    ASSERT_CT_RT(std::strong_ordering::less == std::weak_ordering::less);
    ASSERT_CT_RT(static_cast<std::weak_ordering>(std::strong_ordering::less) == std::weak_ordering::less);
    ASSERT_NOEXCEPT(static_cast<std::weak_ordering>(std::strong_ordering::less));
    ASSERT_CT_RT(std::strong_ordering::less == std::strong_ordering::less);
    ASSERT_NOEXCEPT(std::strong_ordering::less == std::strong_ordering::less);
    ASSERT_CT_RT(!(std::strong_ordering::less == std::strong_ordering::equivalent));
    ASSERT_NOEXCEPT(std::strong_ordering::less == std::strong_ordering::equivalent);
    ASSERT_CT_RT(!(std::strong_ordering::less == std::strong_ordering::equal));
    ASSERT_NOEXCEPT(std::strong_ordering::less == std::strong_ordering::equal);
    ASSERT_CT_RT(!(std::strong_ordering::less == std::strong_ordering::greater));
    ASSERT_NOEXCEPT(std::strong_ordering::less == std::strong_ordering::greater);
    ASSERT_CT_RT(!(std::strong_ordering::less != std::strong_ordering::less));
    ASSERT_NOEXCEPT(std::strong_ordering::less != std::strong_ordering::less);
    ASSERT_CT_RT(std::strong_ordering::less != std::strong_ordering::equivalent);
    ASSERT_NOEXCEPT(std::strong_ordering::less != std::strong_ordering::equivalent);
    ASSERT_CT_RT(std::strong_ordering::less != std::strong_ordering::equal);
    ASSERT_NOEXCEPT(std::strong_ordering::less != std::strong_ordering::equal);
    ASSERT_CT_RT(std::strong_ordering::less != std::strong_ordering::greater);
    ASSERT_NOEXCEPT(std::strong_ordering::less != std::strong_ordering::greater);
    ASSERT_CT_RT(!(std::strong_ordering::equivalent == std::strong_ordering::less));
    ASSERT_NOEXCEPT(std::strong_ordering::equivalent == std::strong_ordering::less);
    ASSERT_CT_RT(!(std::strong_ordering::equal == std::strong_ordering::less));
    ASSERT_NOEXCEPT(std::strong_ordering::equal == std::strong_ordering::less);
    ASSERT_CT_RT(!(std::strong_ordering::greater == std::strong_ordering::less));
    ASSERT_NOEXCEPT(std::strong_ordering::greater == std::strong_ordering::less);
    ASSERT_CT_RT(std::strong_ordering::equivalent != std::strong_ordering::less);
    ASSERT_NOEXCEPT(std::strong_ordering::equivalent != std::strong_ordering::less);
    ASSERT_CT_RT(std::strong_ordering::equal != std::strong_ordering::less);
    ASSERT_NOEXCEPT(std::strong_ordering::equal != std::strong_ordering::less);
    ASSERT_CT_RT(std::strong_ordering::greater != std::strong_ordering::less);
    ASSERT_NOEXCEPT(std::strong_ordering::greater != std::strong_ordering::less);
    ASSERT_CT_RT(!(std::strong_ordering::less == 0));
    ASSERT_NOEXCEPT(std::strong_ordering::less == 0);
    ASSERT_CT_RT(std::strong_ordering::less != 0);
    ASSERT_NOEXCEPT(std::strong_ordering::less != 0);
    ASSERT_CT_RT(std::strong_ordering::less < 0);
    ASSERT_NOEXCEPT(std::strong_ordering::less < 0);
    ASSERT_CT_RT(!(std::strong_ordering::less > 0));
    ASSERT_NOEXCEPT(std::strong_ordering::less > 0);
    ASSERT_CT_RT(std::strong_ordering::less <= 0);
    ASSERT_NOEXCEPT(std::strong_ordering::less <= 0);
    ASSERT_CT_RT(!(std::strong_ordering::less >= 0));
    ASSERT_NOEXCEPT(std::strong_ordering::less >= 0);
    ASSERT_CT_RT(!(0 == std::strong_ordering::less));
    ASSERT_NOEXCEPT(0 == std::strong_ordering::less);
    ASSERT_CT_RT(0 != std::strong_ordering::less);
    ASSERT_NOEXCEPT(0 != std::strong_ordering::less);
    ASSERT_CT_RT(!(0 < std::strong_ordering::less));
    ASSERT_NOEXCEPT(0 < std::strong_ordering::less);
    ASSERT_CT_RT(0 > std::strong_ordering::less);
    ASSERT_NOEXCEPT(0 > std::strong_ordering::less);
    ASSERT_CT_RT(!(0 <= std::strong_ordering::less));
    ASSERT_NOEXCEPT(0 <= std::strong_ordering::less);
    ASSERT_CT_RT(0 >= std::strong_ordering::less);
    ASSERT_NOEXCEPT(0 >= std::strong_ordering::less);
    ASSERT_CT_RT((std::strong_ordering::less <=> 0) == std::strong_ordering::less);
    ASSERT_NOEXCEPT(std::strong_ordering::less <=> 0);
    ASSERT_CT_RT((0 <=> std::strong_ordering::less) == std::strong_ordering::greater);
    ASSERT_NOEXCEPT(0 <=> std::strong_ordering::less);
}

TEST(equal) {
    ASSERT_TYPE(const std::strong_ordering&, std::strong_ordering::equal);
    ASSERT_CT_RT(implicit_conversion_to_partial_ordering(std::strong_ordering::equal));
    ASSERT_CT_RT(std::strong_ordering::equal == std::partial_ordering::equivalent);
    ASSERT_CT_RT(static_cast<std::partial_ordering>(std::strong_ordering::equal) == std::partial_ordering::equivalent);
    ASSERT_NOEXCEPT(static_cast<std::partial_ordering>(std::strong_ordering::equal));
    ASSERT_CT_RT(implicit_conversion_to_weak_ordering(std::strong_ordering::equal));
    ASSERT_CT_RT(std::strong_ordering::equal == std::weak_ordering::equivalent);
    ASSERT_CT_RT(static_cast<std::weak_ordering>(std::strong_ordering::equal) == std::weak_ordering::equivalent);
    ASSERT_NOEXCEPT(static_cast<std::weak_ordering>(std::strong_ordering::equal));
    ASSERT_CT_RT(!(std::strong_ordering::equal == std::strong_ordering::less));
    ASSERT_NOEXCEPT(std::strong_ordering::equal == std::strong_ordering::less);
    ASSERT_CT_RT(std::strong_ordering::equal == std::strong_ordering::equal);
    ASSERT_NOEXCEPT(std::strong_ordering::equal == std::strong_ordering::equal);
    ASSERT_CT_RT(std::strong_ordering::equal == std::strong_ordering::equivalent);
    ASSERT_NOEXCEPT(std::strong_ordering::equal == std::strong_ordering::equivalent);
    ASSERT_CT_RT(!(std::strong_ordering::equal == std::strong_ordering::greater));
    ASSERT_NOEXCEPT(std::strong_ordering::equal == std::strong_ordering::greater);
    ASSERT_CT_RT(std::strong_ordering::equal != std::strong_ordering::less);
    ASSERT_NOEXCEPT(std::strong_ordering::equal != std::strong_ordering::less);
    ASSERT_CT_RT(!(std::strong_ordering::equal != std::strong_ordering::equal));
    ASSERT_NOEXCEPT(std::strong_ordering::equal != std::strong_ordering::equal);
    ASSERT_CT_RT(!(std::strong_ordering::equal != std::strong_ordering::equivalent));
    ASSERT_NOEXCEPT(std::strong_ordering::equal != std::strong_ordering::equivalent);
    ASSERT_CT_RT(std::strong_ordering::equal != std::strong_ordering::greater);
    ASSERT_NOEXCEPT(std::strong_ordering::equal != std::strong_ordering::greater);
    ASSERT_CT_RT(!(std::strong_ordering::less == std::strong_ordering::equal));
    ASSERT_NOEXCEPT(std::strong_ordering::less == std::strong_ordering::equal);
    ASSERT_CT_RT(std::strong_ordering::equivalent == std::strong_ordering::equal);
    ASSERT_NOEXCEPT(std::strong_ordering::equivalent == std::strong_ordering::equal);
    ASSERT_CT_RT(!(std::strong_ordering::greater == std::strong_ordering::equal));
    ASSERT_NOEXCEPT(std::strong_ordering::greater == std::strong_ordering::equal);
    ASSERT_CT_RT(std::strong_ordering::less != std::strong_ordering::equal);
    ASSERT_NOEXCEPT(std::strong_ordering::less != std::strong_ordering::equal);
    ASSERT_CT_RT(!(std::strong_ordering::equivalent != std::strong_ordering::equal));
    ASSERT_NOEXCEPT(std::strong_ordering::equivalent != std::strong_ordering::equal);
    ASSERT_CT_RT(std::strong_ordering::greater != std::strong_ordering::equal);
    ASSERT_NOEXCEPT(std::strong_ordering::greater != std::strong_ordering::equal);
    ASSERT_CT_RT(std::strong_ordering::equal == 0);
    ASSERT_NOEXCEPT(std::strong_ordering::equal == 0);
    ASSERT_CT_RT(!(std::strong_ordering::equal != 0));
    ASSERT_NOEXCEPT(std::strong_ordering::equal != 0);
    ASSERT_CT_RT(!(std::strong_ordering::equal < 0));
    ASSERT_NOEXCEPT(std::strong_ordering::equal < 0);
    ASSERT_CT_RT(!(std::strong_ordering::equal > 0));
    ASSERT_NOEXCEPT(std::strong_ordering::equal > 0);
    ASSERT_CT_RT(std::strong_ordering::equal <= 0);
    ASSERT_NOEXCEPT(std::strong_ordering::equal <= 0);
    ASSERT_CT_RT(std::strong_ordering::equal >= 0);
    ASSERT_NOEXCEPT(std::strong_ordering::equal >= 0);
    ASSERT_CT_RT(0 == std::strong_ordering::equal);
    ASSERT_NOEXCEPT(0 == std::strong_ordering::equal);
    ASSERT_CT_RT(!(0 != std::strong_ordering::equal));
    ASSERT_NOEXCEPT(0 != std::strong_ordering::equal);
    ASSERT_CT_RT(!(0 < std::strong_ordering::equal));
    ASSERT_NOEXCEPT(0 < std::strong_ordering::equal);
    ASSERT_CT_RT(!(0 > std::strong_ordering::equal));
    ASSERT_NOEXCEPT(0 > std::strong_ordering::equal);
    ASSERT_CT_RT(0 <= std::strong_ordering::equal);
    ASSERT_NOEXCEPT(0 <= std::strong_ordering::equal);
    ASSERT_CT_RT(0 >= std::strong_ordering::equal);
    ASSERT_NOEXCEPT(0 >= std::strong_ordering::equal);
    ASSERT_CT_RT((std::strong_ordering::equal <=> 0) == std::strong_ordering::equal);
    ASSERT_NOEXCEPT(std::strong_ordering::equal <=> 0);
    ASSERT_CT_RT((0 <=> std::strong_ordering::equal) == std::strong_ordering::equal);
    ASSERT_NOEXCEPT(0 <=> std::strong_ordering::equal);
}

TEST(equivalent) {
    ASSERT_TYPE(const std::strong_ordering&, std::strong_ordering::equivalent);
    ASSERT_CT_RT(implicit_conversion_to_partial_ordering(std::strong_ordering::equivalent));
    ASSERT_CT_RT(std::strong_ordering::equivalent == std::partial_ordering::equivalent);
    ASSERT_CT_RT(static_cast<std::partial_ordering>(std::strong_ordering::equivalent) == std::partial_ordering::equivalent);
    ASSERT_NOEXCEPT(static_cast<std::partial_ordering>(std::strong_ordering::equivalent));
    ASSERT_CT_RT(implicit_conversion_to_weak_ordering(std::strong_ordering::equivalent));
    ASSERT_CT_RT(std::strong_ordering::equivalent == std::weak_ordering::equivalent);
    ASSERT_CT_RT(static_cast<std::weak_ordering>(std::strong_ordering::equivalent) == std::weak_ordering::equivalent);
    ASSERT_NOEXCEPT(static_cast<std::weak_ordering>(std::strong_ordering::equivalent));
    ASSERT_CT_RT(!(std::strong_ordering::equivalent == std::strong_ordering::less));
    ASSERT_NOEXCEPT(std::strong_ordering::equivalent == std::strong_ordering::less);
    ASSERT_CT_RT(std::strong_ordering::equivalent == std::strong_ordering::equivalent);
    ASSERT_NOEXCEPT(std::strong_ordering::equivalent == std::strong_ordering::equivalent);
    ASSERT_CT_RT(std::strong_ordering::equivalent == std::strong_ordering::equal);
    ASSERT_NOEXCEPT(std::strong_ordering::equivalent == std::strong_ordering::equal);
    ASSERT_CT_RT(!(std::strong_ordering::equivalent == std::strong_ordering::greater));
    ASSERT_NOEXCEPT(std::strong_ordering::equivalent == std::strong_ordering::greater);
    ASSERT_CT_RT(std::strong_ordering::equivalent != std::strong_ordering::less);
    ASSERT_NOEXCEPT(std::strong_ordering::equivalent != std::strong_ordering::less);
    ASSERT_CT_RT(!(std::strong_ordering::equivalent != std::strong_ordering::equal));
    ASSERT_NOEXCEPT(std::strong_ordering::equivalent != std::strong_ordering::equal);
    ASSERT_CT_RT(!(std::strong_ordering::equivalent != std::strong_ordering::equivalent));
    ASSERT_NOEXCEPT(std::strong_ordering::equivalent != std::strong_ordering::equivalent);
    ASSERT_CT_RT(std::strong_ordering::equivalent != std::strong_ordering::greater);
    ASSERT_NOEXCEPT(std::strong_ordering::equivalent != std::strong_ordering::greater);
    ASSERT_CT_RT(!(std::strong_ordering::less == std::strong_ordering::equivalent));
    ASSERT_NOEXCEPT(std::strong_ordering::less == std::strong_ordering::equivalent);
    ASSERT_CT_RT(std::strong_ordering::equal == std::strong_ordering::equivalent);
    ASSERT_NOEXCEPT(std::strong_ordering::equal == std::strong_ordering::equivalent);
    ASSERT_CT_RT(!(std::strong_ordering::greater == std::strong_ordering::equivalent));
    ASSERT_NOEXCEPT(std::strong_ordering::greater == std::strong_ordering::equivalent);
    ASSERT_CT_RT(std::strong_ordering::less != std::strong_ordering::equivalent);
    ASSERT_NOEXCEPT(std::strong_ordering::less != std::strong_ordering::equivalent);
    ASSERT_CT_RT(!(std::strong_ordering::equal != std::strong_ordering::equivalent));
    ASSERT_NOEXCEPT(std::strong_ordering::equal != std::strong_ordering::equivalent);
    ASSERT_CT_RT(std::strong_ordering::greater != std::strong_ordering::equivalent);
    ASSERT_NOEXCEPT(std::strong_ordering::greater != std::strong_ordering::equivalent);
    ASSERT_CT_RT(std::strong_ordering::equivalent == 0);
    ASSERT_NOEXCEPT(std::strong_ordering::equivalent == 0);
    ASSERT_CT_RT(!(std::strong_ordering::equivalent != 0));
    ASSERT_NOEXCEPT(std::strong_ordering::equivalent != 0);
    ASSERT_CT_RT(!(std::strong_ordering::equivalent < 0));
    ASSERT_NOEXCEPT(std::strong_ordering::equivalent < 0);
    ASSERT_CT_RT(!(std::strong_ordering::equivalent > 0));
    ASSERT_NOEXCEPT(std::strong_ordering::equivalent > 0);
    ASSERT_CT_RT(std::strong_ordering::equivalent <= 0);
    ASSERT_NOEXCEPT(std::strong_ordering::equivalent <= 0);
    ASSERT_CT_RT(std::strong_ordering::equivalent >= 0);
    ASSERT_NOEXCEPT(std::strong_ordering::equivalent >= 0);
    ASSERT_CT_RT(0 == std::strong_ordering::equivalent);
    ASSERT_NOEXCEPT(0 == std::strong_ordering::equivalent);
    ASSERT_CT_RT(!(0 != std::strong_ordering::equivalent));
    ASSERT_NOEXCEPT(0 != std::strong_ordering::equivalent);
    ASSERT_CT_RT(!(0 < std::strong_ordering::equivalent));
    ASSERT_NOEXCEPT(0 < std::strong_ordering::equivalent);
    ASSERT_CT_RT(!(0 > std::strong_ordering::equivalent));
    ASSERT_NOEXCEPT(0 > std::strong_ordering::equivalent);
    ASSERT_CT_RT(0 <= std::strong_ordering::equivalent);
    ASSERT_NOEXCEPT(0 <= std::strong_ordering::equivalent);
    ASSERT_CT_RT(0 >= std::strong_ordering::equivalent);
    ASSERT_NOEXCEPT(0 >= std::strong_ordering::equivalent);
    ASSERT_CT_RT((std::strong_ordering::equivalent <=> 0) == std::strong_ordering::equivalent);
    ASSERT_NOEXCEPT(std::strong_ordering::equivalent <=> 0);
    ASSERT_CT_RT((0 <=> std::strong_ordering::equivalent) == std::strong_ordering::equivalent);
    ASSERT_NOEXCEPT(0 <=> std::strong_ordering::equivalent);
}

TEST(greater) {
    ASSERT_TYPE(const std::strong_ordering&, std::strong_ordering::greater);
    ASSERT_CT_RT(implicit_conversion_to_partial_ordering(std::strong_ordering::greater));
    ASSERT_CT_RT(std::strong_ordering::greater == std::partial_ordering::greater);
    ASSERT_CT_RT(static_cast<std::partial_ordering>(std::strong_ordering::greater) == std::partial_ordering::greater);
    ASSERT_NOEXCEPT(static_cast<std::partial_ordering>(std::strong_ordering::greater));
    ASSERT_CT_RT(implicit_conversion_to_weak_ordering(std::strong_ordering::greater));
    ASSERT_CT_RT(std::strong_ordering::greater == std::weak_ordering::greater);
    ASSERT_CT_RT(static_cast<std::weak_ordering>(std::strong_ordering::greater) == std::weak_ordering::greater);
    ASSERT_NOEXCEPT(static_cast<std::weak_ordering>(std::strong_ordering::greater));
    ASSERT_CT_RT(!(std::strong_ordering::greater == std::strong_ordering::less));
    ASSERT_NOEXCEPT(std::strong_ordering::greater == std::strong_ordering::less);
    ASSERT_CT_RT(!(std::strong_ordering::greater == std::strong_ordering::equivalent));
    ASSERT_NOEXCEPT(std::strong_ordering::greater == std::strong_ordering::equivalent);
    ASSERT_CT_RT(!(std::strong_ordering::greater == std::strong_ordering::equal));
    ASSERT_NOEXCEPT(std::strong_ordering::greater == std::strong_ordering::equal);
    ASSERT_CT_RT(std::strong_ordering::greater == std::strong_ordering::greater);
    ASSERT_NOEXCEPT(std::strong_ordering::greater == std::strong_ordering::greater);
    ASSERT_CT_RT(std::strong_ordering::greater != std::strong_ordering::less);
    ASSERT_NOEXCEPT(std::strong_ordering::greater != std::strong_ordering::less);
    ASSERT_CT_RT(std::strong_ordering::greater != std::strong_ordering::equivalent);
    ASSERT_NOEXCEPT(std::strong_ordering::greater != std::strong_ordering::equivalent);
    ASSERT_CT_RT(std::strong_ordering::greater != std::strong_ordering::equal);
    ASSERT_NOEXCEPT(std::strong_ordering::greater != std::strong_ordering::equal);
    ASSERT_CT_RT(!(std::strong_ordering::greater != std::strong_ordering::greater));
    ASSERT_NOEXCEPT(std::strong_ordering::greater != std::strong_ordering::greater);
    ASSERT_CT_RT(!(std::strong_ordering::less == std::strong_ordering::greater));
    ASSERT_NOEXCEPT(std::strong_ordering::less == std::strong_ordering::greater);
    ASSERT_CT_RT(!(std::strong_ordering::equivalent == std::strong_ordering::greater));
    ASSERT_NOEXCEPT(std::strong_ordering::equivalent == std::strong_ordering::greater);
    ASSERT_CT_RT(!(std::strong_ordering::equal == std::strong_ordering::greater));
    ASSERT_NOEXCEPT(std::strong_ordering::equal == std::strong_ordering::greater);
    ASSERT_CT_RT(std::strong_ordering::less != std::strong_ordering::greater);
    ASSERT_NOEXCEPT(std::strong_ordering::less != std::strong_ordering::greater);
    ASSERT_CT_RT(std::strong_ordering::equivalent != std::strong_ordering::greater);
    ASSERT_NOEXCEPT(std::strong_ordering::equivalent != std::strong_ordering::greater);
    ASSERT_CT_RT(std::strong_ordering::equal != std::strong_ordering::greater);
    ASSERT_NOEXCEPT(std::strong_ordering::equal != std::strong_ordering::greater);
    ASSERT_CT_RT(!(std::strong_ordering::greater == 0));
    ASSERT_NOEXCEPT(std::strong_ordering::greater == 0);
    ASSERT_CT_RT(std::strong_ordering::greater != 0);
    ASSERT_NOEXCEPT(std::strong_ordering::greater != 0);
    ASSERT_CT_RT(!(std::strong_ordering::greater < 0));
    ASSERT_NOEXCEPT(std::strong_ordering::greater < 0);
    ASSERT_CT_RT(std::strong_ordering::greater > 0);
    ASSERT_NOEXCEPT(std::strong_ordering::greater > 0);
    ASSERT_CT_RT(!(std::strong_ordering::greater <= 0));
    ASSERT_NOEXCEPT(std::strong_ordering::greater <= 0);
    ASSERT_CT_RT(std::strong_ordering::greater >= 0);
    ASSERT_NOEXCEPT(std::strong_ordering::greater >= 0);
    ASSERT_CT_RT(!(0 == std::strong_ordering::greater));
    ASSERT_NOEXCEPT(0 == std::strong_ordering::greater);
    ASSERT_CT_RT(0 != std::strong_ordering::greater);
    ASSERT_NOEXCEPT(0 != std::strong_ordering::greater);
    ASSERT_CT_RT(0 < std::strong_ordering::greater);
    ASSERT_NOEXCEPT(0 < std::strong_ordering::greater);
    ASSERT_CT_RT(!(0 > std::strong_ordering::greater));
    ASSERT_NOEXCEPT(0 > std::strong_ordering::greater);
    ASSERT_CT_RT(0 <= std::strong_ordering::greater);
    ASSERT_NOEXCEPT(0 <= std::strong_ordering::greater);
    ASSERT_CT_RT(!(0 >= std::strong_ordering::greater));
    ASSERT_NOEXCEPT(0 >= std::strong_ordering::greater);
    ASSERT_CT_RT((std::strong_ordering::greater <=> 0) == std::strong_ordering::greater);
    ASSERT_NOEXCEPT(std::strong_ordering::greater <=> 0);
    ASSERT_CT_RT((0 <=> std::strong_ordering::greater) == std::strong_ordering::less);
    ASSERT_NOEXCEPT(0 <=> std::strong_ordering::greater);
}
