#include <compare>

#include "testing.h"

TEST(less) {
    ASSERT_TYPE(const std::partial_ordering&, std::partial_ordering::less);
    ASSERT_CT_RT(std::partial_ordering::less == std::partial_ordering::less);
    ASSERT_NOEXCEPT(std::partial_ordering::less == std::partial_ordering::less);
    ASSERT_CT_RT(!(std::partial_ordering::less == std::partial_ordering::unordered));
    ASSERT_NOEXCEPT(std::partial_ordering::less == std::partial_ordering::unordered);
    ASSERT_CT_RT(!(std::partial_ordering::less == std::partial_ordering::equivalent));
    ASSERT_NOEXCEPT(std::partial_ordering::less == std::partial_ordering::equivalent);
    ASSERT_CT_RT(!(std::partial_ordering::less == std::partial_ordering::greater));
    ASSERT_NOEXCEPT(std::partial_ordering::less == std::partial_ordering::greater);
    ASSERT_CT_RT(!(std::partial_ordering::less != std::partial_ordering::less));
    ASSERT_NOEXCEPT(std::partial_ordering::less != std::partial_ordering::less);
    ASSERT_CT_RT(std::partial_ordering::less != std::partial_ordering::unordered);
    ASSERT_NOEXCEPT(std::partial_ordering::less != std::partial_ordering::unordered);
    ASSERT_CT_RT(std::partial_ordering::less != std::partial_ordering::equivalent);
    ASSERT_NOEXCEPT(std::partial_ordering::less != std::partial_ordering::equivalent);
    ASSERT_CT_RT(std::partial_ordering::less != std::partial_ordering::greater);
    ASSERT_NOEXCEPT(std::partial_ordering::less != std::partial_ordering::greater);
    ASSERT_CT_RT(!(std::partial_ordering::less == 0));
    ASSERT_NOEXCEPT(std::partial_ordering::less == 0);
    ASSERT_CT_RT(std::partial_ordering::less != 0);
    ASSERT_NOEXCEPT(std::partial_ordering::less != 0);
    ASSERT_CT_RT(std::partial_ordering::less < 0);
    ASSERT_NOEXCEPT(std::partial_ordering::less < 0);
    ASSERT_CT_RT(std::partial_ordering::less <= 0);
    ASSERT_NOEXCEPT(std::partial_ordering::less <= 0);
    ASSERT_CT_RT(!(std::partial_ordering::less >= 0));
    ASSERT_NOEXCEPT(std::partial_ordering::less >= 0);
    ASSERT_CT_RT(!(std::partial_ordering::less > 0));
    ASSERT_NOEXCEPT(std::partial_ordering::less > 0);
    ASSERT_CT_RT(!(0 == std::partial_ordering::less));
    ASSERT_NOEXCEPT(0 == std::partial_ordering::less);
    ASSERT_CT_RT(0 != std::partial_ordering::less);
    ASSERT_NOEXCEPT(0 != std::partial_ordering::less);
    ASSERT_CT_RT(!(0 < std::partial_ordering::less));
    ASSERT_NOEXCEPT(0 < std::partial_ordering::less);
    ASSERT_CT_RT(!(0 <= std::partial_ordering::less));
    ASSERT_NOEXCEPT(0 <= std::partial_ordering::less);
    ASSERT_CT_RT(0 >= std::partial_ordering::less);
    ASSERT_NOEXCEPT(0 >= std::partial_ordering::less);
    ASSERT_CT_RT(0 > std::partial_ordering::less);
    ASSERT_NOEXCEPT(0 > std::partial_ordering::less);
    ASSERT_CT_RT((std::partial_ordering::less <=> 0) == std::partial_ordering::less);
    ASSERT_NOEXCEPT(std::partial_ordering::less <=> 0);
    ASSERT_CT_RT((0 <=> std::partial_ordering::less) == std::partial_ordering::greater);
    ASSERT_NOEXCEPT(0 <=> std::partial_ordering::less);
}

TEST(equivalent) {
    ASSERT_TYPE(const std::partial_ordering&, std::partial_ordering::equivalent);
    ASSERT_CT_RT(!(std::partial_ordering::equivalent == std::partial_ordering::less));
    ASSERT_NOEXCEPT(std::partial_ordering::equivalent == std::partial_ordering::less);
    ASSERT_CT_RT(!(std::partial_ordering::equivalent == std::partial_ordering::unordered));
    ASSERT_NOEXCEPT(std::partial_ordering::equivalent == std::partial_ordering::unordered);
    ASSERT_CT_RT(std::partial_ordering::equivalent == std::partial_ordering::equivalent);
    ASSERT_NOEXCEPT(std::partial_ordering::equivalent == std::partial_ordering::equivalent);
    ASSERT_CT_RT(!(std::partial_ordering::equivalent == std::partial_ordering::greater));
    ASSERT_NOEXCEPT(std::partial_ordering::equivalent == std::partial_ordering::greater);
    ASSERT_CT_RT(std::partial_ordering::equivalent != std::partial_ordering::less);
    ASSERT_NOEXCEPT(std::partial_ordering::equivalent != std::partial_ordering::less);
    ASSERT_CT_RT(std::partial_ordering::equivalent != std::partial_ordering::unordered);
    ASSERT_NOEXCEPT(std::partial_ordering::equivalent != std::partial_ordering::unordered);
    ASSERT_CT_RT(!(std::partial_ordering::equivalent != std::partial_ordering::equivalent));
    ASSERT_NOEXCEPT(std::partial_ordering::equivalent != std::partial_ordering::equivalent);
    ASSERT_CT_RT(std::partial_ordering::equivalent != std::partial_ordering::greater);
    ASSERT_NOEXCEPT(std::partial_ordering::equivalent != std::partial_ordering::greater);
    ASSERT_CT_RT(std::partial_ordering::equivalent == 0);
    ASSERT_NOEXCEPT(std::partial_ordering::equivalent == 0);
    ASSERT_CT_RT(!(std::partial_ordering::equivalent != 0));
    ASSERT_NOEXCEPT(std::partial_ordering::equivalent != 0);
    ASSERT_CT_RT(!(std::partial_ordering::equivalent < 0));
    ASSERT_NOEXCEPT(std::partial_ordering::equivalent < 0);
    ASSERT_CT_RT(std::partial_ordering::equivalent <= 0);
    ASSERT_NOEXCEPT(std::partial_ordering::equivalent <= 0);
    ASSERT_CT_RT(std::partial_ordering::equivalent >= 0);
    ASSERT_NOEXCEPT(std::partial_ordering::equivalent >= 0);
    ASSERT_CT_RT(!(std::partial_ordering::equivalent > 0));
    ASSERT_NOEXCEPT(std::partial_ordering::equivalent > 0);
    ASSERT_CT_RT(0 == std::partial_ordering::equivalent);
    ASSERT_NOEXCEPT(0 == std::partial_ordering::equivalent);
    ASSERT_CT_RT(!(0 != std::partial_ordering::equivalent));
    ASSERT_NOEXCEPT(0 != std::partial_ordering::equivalent);
    ASSERT_CT_RT(!(0 < std::partial_ordering::equivalent));
    ASSERT_NOEXCEPT(0 < std::partial_ordering::equivalent);
    ASSERT_CT_RT(0 <= std::partial_ordering::equivalent);
    ASSERT_NOEXCEPT(0 <= std::partial_ordering::equivalent);
    ASSERT_CT_RT(0 >= std::partial_ordering::equivalent);
    ASSERT_NOEXCEPT(0 >= std::partial_ordering::equivalent);
    ASSERT_CT_RT(!(0 > std::partial_ordering::equivalent));
    ASSERT_NOEXCEPT(0 > std::partial_ordering::equivalent);
    ASSERT_CT_RT((std::partial_ordering::equivalent <=> 0) == std::partial_ordering::equivalent);
    ASSERT_NOEXCEPT(std::partial_ordering::equivalent <=> 0);
    ASSERT_CT_RT((0 <=> std::partial_ordering::equivalent) == std::partial_ordering::equivalent);
    ASSERT_NOEXCEPT(0 <=> std::partial_ordering::equivalent);
}

TEST(greater) {
    ASSERT_TYPE(const std::partial_ordering&, std::partial_ordering::greater);
    ASSERT_CT_RT(!(std::partial_ordering::greater == std::partial_ordering::less));
    ASSERT_NOEXCEPT(std::partial_ordering::greater == std::partial_ordering::less);
    ASSERT_CT_RT(!(std::partial_ordering::greater == std::partial_ordering::unordered));
    ASSERT_NOEXCEPT(std::partial_ordering::greater == std::partial_ordering::unordered);
    ASSERT_CT_RT(!(std::partial_ordering::greater == std::partial_ordering::equivalent));
    ASSERT_NOEXCEPT(std::partial_ordering::greater == std::partial_ordering::equivalent);
    ASSERT_CT_RT(std::partial_ordering::greater == std::partial_ordering::greater);
    ASSERT_NOEXCEPT(std::partial_ordering::greater == std::partial_ordering::greater);
    ASSERT_CT_RT(std::partial_ordering::greater != std::partial_ordering::less);
    ASSERT_NOEXCEPT(std::partial_ordering::greater != std::partial_ordering::less);
    ASSERT_CT_RT(std::partial_ordering::greater != std::partial_ordering::unordered);
    ASSERT_NOEXCEPT(std::partial_ordering::greater != std::partial_ordering::unordered);
    ASSERT_CT_RT(std::partial_ordering::greater != std::partial_ordering::equivalent);
    ASSERT_NOEXCEPT(std::partial_ordering::greater != std::partial_ordering::equivalent);
    ASSERT_CT_RT(!(std::partial_ordering::greater != std::partial_ordering::greater));
    ASSERT_NOEXCEPT(std::partial_ordering::greater != std::partial_ordering::greater);
    ASSERT_CT_RT(!(std::partial_ordering::greater == 0));
    ASSERT_NOEXCEPT(std::partial_ordering::greater == 0);
    ASSERT_CT_RT(std::partial_ordering::greater != 0);
    ASSERT_NOEXCEPT(std::partial_ordering::greater != 0);
    ASSERT_CT_RT(!(std::partial_ordering::greater < 0));
    ASSERT_NOEXCEPT(std::partial_ordering::greater < 0);
    ASSERT_CT_RT(!(std::partial_ordering::greater <= 0));
    ASSERT_NOEXCEPT(std::partial_ordering::greater <= 0);
    ASSERT_CT_RT(std::partial_ordering::greater >= 0);
    ASSERT_NOEXCEPT(std::partial_ordering::greater >= 0);
    ASSERT_CT_RT(std::partial_ordering::greater > 0);
    ASSERT_NOEXCEPT(std::partial_ordering::greater > 0);
    ASSERT_CT_RT(!(0 == std::partial_ordering::greater));
    ASSERT_NOEXCEPT(0 == std::partial_ordering::greater);
    ASSERT_CT_RT(0 != std::partial_ordering::greater);
    ASSERT_NOEXCEPT(0 != std::partial_ordering::greater);
    ASSERT_CT_RT(0 < std::partial_ordering::greater);
    ASSERT_NOEXCEPT(0 < std::partial_ordering::greater);
    ASSERT_CT_RT(0 <= std::partial_ordering::greater);
    ASSERT_NOEXCEPT(0 <= std::partial_ordering::greater);
    ASSERT_CT_RT(!(0 >= std::partial_ordering::greater));
    ASSERT_NOEXCEPT(0 >= std::partial_ordering::greater);
    ASSERT_CT_RT(!(0 > std::partial_ordering::greater));
    ASSERT_NOEXCEPT(0 > std::partial_ordering::greater);
    ASSERT_CT_RT((std::partial_ordering::greater <=> 0) == std::partial_ordering::greater);
    ASSERT_NOEXCEPT(std::partial_ordering::greater <=> 0);
    ASSERT_CT_RT((0 <=> std::partial_ordering::greater) == std::partial_ordering::less);
    ASSERT_NOEXCEPT(0 <=> std::partial_ordering::greater);
}

TEST(unordered) {
    ASSERT_TYPE(const std::partial_ordering&, std::partial_ordering::unordered);
    ASSERT_CT_RT(!(std::partial_ordering::unordered == std::partial_ordering::less));
    ASSERT_NOEXCEPT(std::partial_ordering::unordered == std::partial_ordering::less);
    ASSERT_CT_RT(std::partial_ordering::unordered == std::partial_ordering::unordered);
    ASSERT_NOEXCEPT(std::partial_ordering::unordered == std::partial_ordering::unordered);
    ASSERT_CT_RT(!(std::partial_ordering::unordered == std::partial_ordering::greater));
    ASSERT_NOEXCEPT(std::partial_ordering::unordered == std::partial_ordering::greater);
    ASSERT_CT_RT(!(std::partial_ordering::unordered == std::partial_ordering::equivalent));
    ASSERT_NOEXCEPT(std::partial_ordering::unordered == std::partial_ordering::equivalent);
    ASSERT_CT_RT(std::partial_ordering::unordered != std::partial_ordering::less);
    ASSERT_NOEXCEPT(std::partial_ordering::unordered != std::partial_ordering::less);
    ASSERT_CT_RT(!(std::partial_ordering::unordered != std::partial_ordering::unordered));
    ASSERT_NOEXCEPT(std::partial_ordering::unordered != std::partial_ordering::unordered);
    ASSERT_CT_RT(std::partial_ordering::unordered != std::partial_ordering::greater);
    ASSERT_NOEXCEPT(std::partial_ordering::unordered != std::partial_ordering::greater);
    ASSERT_CT_RT(std::partial_ordering::unordered != std::partial_ordering::equivalent);
    ASSERT_NOEXCEPT(std::partial_ordering::unordered != std::partial_ordering::equivalent);
    ASSERT_CT_RT(!(std::partial_ordering::unordered == 0));
    ASSERT_NOEXCEPT(std::partial_ordering::unordered == 0);
    ASSERT_CT_RT(std::partial_ordering::unordered != 0);
    ASSERT_NOEXCEPT(std::partial_ordering::unordered != 0);
    ASSERT_CT_RT(!(std::partial_ordering::unordered < 0));
    ASSERT_NOEXCEPT(std::partial_ordering::unordered < 0);
    ASSERT_CT_RT(!(std::partial_ordering::unordered <= 0));
    ASSERT_NOEXCEPT(std::partial_ordering::unordered <= 0);
    ASSERT_CT_RT(!(std::partial_ordering::unordered >= 0));
    ASSERT_NOEXCEPT(std::partial_ordering::unordered >= 0);
    ASSERT_CT_RT(!(std::partial_ordering::unordered > 0));
    ASSERT_NOEXCEPT(std::partial_ordering::unordered > 0);
    ASSERT_CT_RT(!(0 == std::partial_ordering::unordered));
    ASSERT_NOEXCEPT(0 == std::partial_ordering::unordered);
    ASSERT_CT_RT(0 != std::partial_ordering::unordered);
    ASSERT_NOEXCEPT(0 != std::partial_ordering::unordered);
    ASSERT_CT_RT(!(0 < std::partial_ordering::unordered));
    ASSERT_NOEXCEPT(0 < std::partial_ordering::unordered);
    ASSERT_CT_RT(!(0 <= std::partial_ordering::unordered));
    ASSERT_NOEXCEPT(0 <= std::partial_ordering::unordered);
    ASSERT_CT_RT(!(0 >= std::partial_ordering::unordered));
    ASSERT_NOEXCEPT(0 >= std::partial_ordering::unordered);
    ASSERT_CT_RT(!(0 > std::partial_ordering::unordered));
    ASSERT_NOEXCEPT(0 > std::partial_ordering::unordered);
    ASSERT_CT_RT((std::partial_ordering::unordered <=> 0) == std::partial_ordering::unordered);
    ASSERT_NOEXCEPT(std::partial_ordering::unordered <=> 0);
    ASSERT_CT_RT((0 <=> std::partial_ordering::unordered) == std::partial_ordering::unordered);
    ASSERT_NOEXCEPT(0 <=> std::partial_ordering::unordered);
}
