#include <compare>

#include "testing.h"

TEST(less) {
    expect_type(const std::partial_ordering&, std::partial_ordering::less);
    expect_ct_and_rt(std::partial_ordering::less == std::partial_ordering::less);
    expect_is_noexcept(std::partial_ordering::less == std::partial_ordering::less);
    expect_ct_and_rt(!(std::partial_ordering::less == std::partial_ordering::unordered));
    expect_is_noexcept(std::partial_ordering::less == std::partial_ordering::unordered);
    expect_ct_and_rt(!(std::partial_ordering::less == std::partial_ordering::equivalent));
    expect_is_noexcept(std::partial_ordering::less == std::partial_ordering::equivalent);
    expect_ct_and_rt(!(std::partial_ordering::less == std::partial_ordering::greater));
    expect_is_noexcept(std::partial_ordering::less == std::partial_ordering::greater);
    expect_ct_and_rt(!(std::partial_ordering::less != std::partial_ordering::less));
    expect_is_noexcept(std::partial_ordering::less != std::partial_ordering::less);
    expect_ct_and_rt(std::partial_ordering::less != std::partial_ordering::unordered);
    expect_is_noexcept(std::partial_ordering::less != std::partial_ordering::unordered);
    expect_ct_and_rt(std::partial_ordering::less != std::partial_ordering::equivalent);
    expect_is_noexcept(std::partial_ordering::less != std::partial_ordering::equivalent);
    expect_ct_and_rt(std::partial_ordering::less != std::partial_ordering::greater);
    expect_is_noexcept(std::partial_ordering::less != std::partial_ordering::greater);
    expect_ct_and_rt(!(std::partial_ordering::less == 0));
    expect_is_noexcept(std::partial_ordering::less == 0);
    expect_ct_and_rt(std::partial_ordering::less != 0);
    expect_is_noexcept(std::partial_ordering::less != 0);
    expect_ct_and_rt(std::partial_ordering::less < 0);
    expect_is_noexcept(std::partial_ordering::less < 0);
    expect_ct_and_rt(std::partial_ordering::less <= 0);
    expect_is_noexcept(std::partial_ordering::less <= 0);
    expect_ct_and_rt(!(std::partial_ordering::less >= 0));
    expect_is_noexcept(std::partial_ordering::less >= 0);
    expect_ct_and_rt(!(std::partial_ordering::less > 0));
    expect_is_noexcept(std::partial_ordering::less > 0);
    expect_ct_and_rt(!(0 == std::partial_ordering::less));
    expect_is_noexcept(0 == std::partial_ordering::less);
    expect_ct_and_rt(0 != std::partial_ordering::less);
    expect_is_noexcept(0 != std::partial_ordering::less);
    expect_ct_and_rt(!(0 < std::partial_ordering::less));
    expect_is_noexcept(0 < std::partial_ordering::less);
    expect_ct_and_rt(!(0 <= std::partial_ordering::less));
    expect_is_noexcept(0 <= std::partial_ordering::less);
    expect_ct_and_rt(0 >= std::partial_ordering::less);
    expect_is_noexcept(0 >= std::partial_ordering::less);
    expect_ct_and_rt(0 > std::partial_ordering::less);
    expect_is_noexcept(0 > std::partial_ordering::less);
    expect_ct_and_rt((std::partial_ordering::less <=> 0) == std::partial_ordering::less);
    expect_is_noexcept(std::partial_ordering::less <=> 0);
    expect_ct_and_rt((0 <=> std::partial_ordering::less) == std::partial_ordering::greater);
    expect_is_noexcept(0 <=> std::partial_ordering::less);
}

TEST(equivalent) {
    expect_type(const std::partial_ordering&, std::partial_ordering::equivalent);
    expect_ct_and_rt(!(std::partial_ordering::equivalent == std::partial_ordering::less));
    expect_is_noexcept(std::partial_ordering::equivalent == std::partial_ordering::less);
    expect_ct_and_rt(!(std::partial_ordering::equivalent == std::partial_ordering::unordered));
    expect_is_noexcept(std::partial_ordering::equivalent == std::partial_ordering::unordered);
    expect_ct_and_rt(std::partial_ordering::equivalent == std::partial_ordering::equivalent);
    expect_is_noexcept(std::partial_ordering::equivalent == std::partial_ordering::equivalent);
    expect_ct_and_rt(!(std::partial_ordering::equivalent == std::partial_ordering::greater));
    expect_is_noexcept(std::partial_ordering::equivalent == std::partial_ordering::greater);
    expect_ct_and_rt(std::partial_ordering::equivalent != std::partial_ordering::less);
    expect_is_noexcept(std::partial_ordering::equivalent != std::partial_ordering::less);
    expect_ct_and_rt(std::partial_ordering::equivalent != std::partial_ordering::unordered);
    expect_is_noexcept(std::partial_ordering::equivalent != std::partial_ordering::unordered);
    expect_ct_and_rt(!(std::partial_ordering::equivalent != std::partial_ordering::equivalent));
    expect_is_noexcept(std::partial_ordering::equivalent != std::partial_ordering::equivalent);
    expect_ct_and_rt(std::partial_ordering::equivalent != std::partial_ordering::greater);
    expect_is_noexcept(std::partial_ordering::equivalent != std::partial_ordering::greater);
    expect_ct_and_rt(std::partial_ordering::equivalent == 0);
    expect_is_noexcept(std::partial_ordering::equivalent == 0);
    expect_ct_and_rt(!(std::partial_ordering::equivalent != 0));
    expect_is_noexcept(std::partial_ordering::equivalent != 0);
    expect_ct_and_rt(!(std::partial_ordering::equivalent < 0));
    expect_is_noexcept(std::partial_ordering::equivalent < 0);
    expect_ct_and_rt(std::partial_ordering::equivalent <= 0);
    expect_is_noexcept(std::partial_ordering::equivalent <= 0);
    expect_ct_and_rt(std::partial_ordering::equivalent >= 0);
    expect_is_noexcept(std::partial_ordering::equivalent >= 0);
    expect_ct_and_rt(!(std::partial_ordering::equivalent > 0));
    expect_is_noexcept(std::partial_ordering::equivalent > 0);
    expect_ct_and_rt(0 == std::partial_ordering::equivalent);
    expect_is_noexcept(0 == std::partial_ordering::equivalent);
    expect_ct_and_rt(!(0 != std::partial_ordering::equivalent));
    expect_is_noexcept(0 != std::partial_ordering::equivalent);
    expect_ct_and_rt(!(0 < std::partial_ordering::equivalent));
    expect_is_noexcept(0 < std::partial_ordering::equivalent);
    expect_ct_and_rt(0 <= std::partial_ordering::equivalent);
    expect_is_noexcept(0 <= std::partial_ordering::equivalent);
    expect_ct_and_rt(0 >= std::partial_ordering::equivalent);
    expect_is_noexcept(0 >= std::partial_ordering::equivalent);
    expect_ct_and_rt(!(0 > std::partial_ordering::equivalent));
    expect_is_noexcept(0 > std::partial_ordering::equivalent);
    expect_ct_and_rt((std::partial_ordering::equivalent <=> 0) == std::partial_ordering::equivalent);
    expect_is_noexcept(std::partial_ordering::equivalent <=> 0);
    expect_ct_and_rt((0 <=> std::partial_ordering::equivalent)
                     == std::partial_ordering::equivalent);
    expect_is_noexcept(0 <=> std::partial_ordering::equivalent);
}

TEST(greater) {
    expect_type(const std::partial_ordering&, std::partial_ordering::greater);
    expect_ct_and_rt(!(std::partial_ordering::greater == std::partial_ordering::less));
    expect_is_noexcept(std::partial_ordering::greater == std::partial_ordering::less);
    expect_ct_and_rt(!(std::partial_ordering::greater == std::partial_ordering::unordered));
    expect_is_noexcept(std::partial_ordering::greater == std::partial_ordering::unordered);
    expect_ct_and_rt(!(std::partial_ordering::greater == std::partial_ordering::equivalent));
    expect_is_noexcept(std::partial_ordering::greater == std::partial_ordering::equivalent);
    expect_ct_and_rt(std::partial_ordering::greater == std::partial_ordering::greater);
    expect_is_noexcept(std::partial_ordering::greater == std::partial_ordering::greater);
    expect_ct_and_rt(std::partial_ordering::greater != std::partial_ordering::less);
    expect_is_noexcept(std::partial_ordering::greater != std::partial_ordering::less);
    expect_ct_and_rt(std::partial_ordering::greater != std::partial_ordering::unordered);
    expect_is_noexcept(std::partial_ordering::greater != std::partial_ordering::unordered);
    expect_ct_and_rt(std::partial_ordering::greater != std::partial_ordering::equivalent);
    expect_is_noexcept(std::partial_ordering::greater != std::partial_ordering::equivalent);
    expect_ct_and_rt(!(std::partial_ordering::greater != std::partial_ordering::greater));
    expect_is_noexcept(std::partial_ordering::greater != std::partial_ordering::greater);
    expect_ct_and_rt(!(std::partial_ordering::greater == 0));
    expect_is_noexcept(std::partial_ordering::greater == 0);
    expect_ct_and_rt(std::partial_ordering::greater != 0);
    expect_is_noexcept(std::partial_ordering::greater != 0);
    expect_ct_and_rt(!(std::partial_ordering::greater < 0));
    expect_is_noexcept(std::partial_ordering::greater < 0);
    expect_ct_and_rt(!(std::partial_ordering::greater <= 0));
    expect_is_noexcept(std::partial_ordering::greater <= 0);
    expect_ct_and_rt(std::partial_ordering::greater >= 0);
    expect_is_noexcept(std::partial_ordering::greater >= 0);
    expect_ct_and_rt(std::partial_ordering::greater > 0);
    expect_is_noexcept(std::partial_ordering::greater > 0);
    expect_ct_and_rt(!(0 == std::partial_ordering::greater));
    expect_is_noexcept(0 == std::partial_ordering::greater);
    expect_ct_and_rt(0 != std::partial_ordering::greater);
    expect_is_noexcept(0 != std::partial_ordering::greater);
    expect_ct_and_rt(0 < std::partial_ordering::greater);
    expect_is_noexcept(0 < std::partial_ordering::greater);
    expect_ct_and_rt(0 <= std::partial_ordering::greater);
    expect_is_noexcept(0 <= std::partial_ordering::greater);
    expect_ct_and_rt(!(0 >= std::partial_ordering::greater));
    expect_is_noexcept(0 >= std::partial_ordering::greater);
    expect_ct_and_rt(!(0 > std::partial_ordering::greater));
    expect_is_noexcept(0 > std::partial_ordering::greater);
    expect_ct_and_rt((std::partial_ordering::greater <=> 0) == std::partial_ordering::greater);
    expect_is_noexcept(std::partial_ordering::greater <=> 0);
    expect_ct_and_rt((0 <=> std::partial_ordering::greater) == std::partial_ordering::less);
    expect_is_noexcept(0 <=> std::partial_ordering::greater);
}

TEST(unordered) {
    expect_type(const std::partial_ordering&, std::partial_ordering::unordered);
    expect_ct_and_rt(!(std::partial_ordering::unordered == std::partial_ordering::less));
    expect_is_noexcept(std::partial_ordering::unordered == std::partial_ordering::less);
    expect_ct_and_rt(std::partial_ordering::unordered == std::partial_ordering::unordered);
    expect_is_noexcept(std::partial_ordering::unordered == std::partial_ordering::unordered);
    expect_ct_and_rt(!(std::partial_ordering::unordered == std::partial_ordering::greater));
    expect_is_noexcept(std::partial_ordering::unordered == std::partial_ordering::greater);
    expect_ct_and_rt(!(std::partial_ordering::unordered == std::partial_ordering::equivalent));
    expect_is_noexcept(std::partial_ordering::unordered == std::partial_ordering::equivalent);
    expect_ct_and_rt(std::partial_ordering::unordered != std::partial_ordering::less);
    expect_is_noexcept(std::partial_ordering::unordered != std::partial_ordering::less);
    expect_ct_and_rt(!(std::partial_ordering::unordered != std::partial_ordering::unordered));
    expect_is_noexcept(std::partial_ordering::unordered != std::partial_ordering::unordered);
    expect_ct_and_rt(std::partial_ordering::unordered != std::partial_ordering::greater);
    expect_is_noexcept(std::partial_ordering::unordered != std::partial_ordering::greater);
    expect_ct_and_rt(std::partial_ordering::unordered != std::partial_ordering::equivalent);
    expect_is_noexcept(std::partial_ordering::unordered != std::partial_ordering::equivalent);
    expect_ct_and_rt(!(std::partial_ordering::unordered == 0));
    expect_is_noexcept(std::partial_ordering::unordered == 0);
    expect_ct_and_rt(std::partial_ordering::unordered != 0);
    expect_is_noexcept(std::partial_ordering::unordered != 0);
    expect_ct_and_rt(!(std::partial_ordering::unordered < 0));
    expect_is_noexcept(std::partial_ordering::unordered < 0);
    expect_ct_and_rt(!(std::partial_ordering::unordered <= 0));
    expect_is_noexcept(std::partial_ordering::unordered <= 0);
    expect_ct_and_rt(!(std::partial_ordering::unordered >= 0));
    expect_is_noexcept(std::partial_ordering::unordered >= 0);
    expect_ct_and_rt(!(std::partial_ordering::unordered > 0));
    expect_is_noexcept(std::partial_ordering::unordered > 0);
    expect_ct_and_rt(!(0 == std::partial_ordering::unordered));
    expect_is_noexcept(0 == std::partial_ordering::unordered);
    expect_ct_and_rt(0 != std::partial_ordering::unordered);
    expect_is_noexcept(0 != std::partial_ordering::unordered);
    expect_ct_and_rt(!(0 < std::partial_ordering::unordered));
    expect_is_noexcept(0 < std::partial_ordering::unordered);
    expect_ct_and_rt(!(0 <= std::partial_ordering::unordered));
    expect_is_noexcept(0 <= std::partial_ordering::unordered);
    expect_ct_and_rt(!(0 >= std::partial_ordering::unordered));
    expect_is_noexcept(0 >= std::partial_ordering::unordered);
    expect_ct_and_rt(!(0 > std::partial_ordering::unordered));
    expect_is_noexcept(0 > std::partial_ordering::unordered);
    expect_ct_and_rt((std::partial_ordering::unordered <=> 0) == std::partial_ordering::unordered);
    expect_is_noexcept(std::partial_ordering::unordered <=> 0);
    expect_ct_and_rt((0 <=> std::partial_ordering::unordered) == std::partial_ordering::unordered);
    expect_is_noexcept(0 <=> std::partial_ordering::unordered);
}
