name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  clang-macos:
    strategy:
      matrix:
        build_type: [ Debug, Release ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check
        run: ${{github.workspace}}/tools/scripts/check_ci.sh clang clang++ ${{ matrix.build_type }}

  clang-ubuntu-22-04:
    strategy:
      matrix:
        build_type: [ Debug, Release ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Clang
        run: sudo apt install -y clang
      - name: Check
        run: ${{github.workspace}}/tools/scripts/check_ci.sh clang clang++ ${{ matrix.build_type }}

  gcc-ubuntu-22-04:
    strategy:
      matrix:
        build_type: [ Debug, Release ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install GCC
        run: sudo apt install -y gcc g++
      - name: Check
        run: ${{github.workspace}}/tools/scripts/check_ci.sh gcc g++ ${{ matrix.build_type }}
