name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-clang:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
        build_type: [ Debug, Release ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install LLVM
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "14.0"
          directory: ${{github.workspace}}/llvm

      - name: Check
        run: ${{github.workspace}}/ci-check.sh
        env:
          CC: clang
          CXX: clang++
          CMAKE_BUILD_TYPE: ${{ matrix.build_type }}

  check-gcc:
    strategy:
      matrix:
        build_type: [ Debug, Release ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
          platform: x64

      - name: Check
        run: ${{github.workspace}}/ci-check.sh
        env:
          CC: gcc
          CXX: g++
          CMAKE_BUILD_TYPE: ${{ matrix.build_type }}
